- id: python-todo
  name: python-todo
  entry: python_todo.bash
  language: script
  types: [python]
- id: javascript-todo
  name: javascript-todo
  entry: javascript_todo.bash
  language: script
  types: [javascript]