- id: python-todo
  name: python-todo
  entry: python_todo.bash
  language: script
  types: [python]
- id: javascript-todo
  name: javascript-todo
  entry: javascript_todo.bash
  language: script
  types: [javascript]
- id: pygrep-todo
  name: check for TODO like comments
  description: "A quick check for TODO like comments"
  entry: '((#|//) (\?|TODO|FIXME|XXX|BUG|HACK))|\[ \]|\[x\]'
  language: pygrep
